### ISSUE TITLE
セッションのスライドでDroidKaigiのロゴを使用

### ISSUE THREAD

**Issue by yurihondo** [DroidKaigi/visual-identity#1]
To 担当者様

お世話になっております。

掲題の件について質問をさせて下さい。
自身のDroidKaigi2020の発表スライドで以下のようにDroidKaigiのロゴを使用させて頂きたいと考えております。
こちら、ロゴの使用自体が可能かどうかをご教示頂けないでしょうか？
<img src="https://user-images.githubusercontent.com/33515193/74432651-43f4b300-4ea2-11ea-922e-0bc82c7e4828.png" width="320px">
※表紙のスライドにしか使いません
※対象となる発表はDay2(02/21)にDialogsの部屋で16:00-16:40に行われる
 `瀕死のシステムが強くなって復活する話`のセッションです。

もし、こういった用途で使用不可であったり、
使用するに当たってケアすべき事項などがある場合その旨お伝え頂けると幸いでございます。

お忙しい中大変恐縮でございますが、ご確認をよろしくお願いいたします。

**Comment by mutoatu** [comment]
@yurihondo 
ご質問ありがとうございます！
また、使用している箇所の画像を添付頂きありがとうございます。

こちら問題ありませんので、このままご使用ください 🙇

**Comment by yurihondo** [comment]
@mutoatu 
ご確認ありがとうございます。
では、このまま使用させていただきます。
迅速にお返事頂けて非常に助かりました。
